version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: smartpickup
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      # L'URL utilise le nom du service "db" pour se connecter
      - DATABASE_URL=postgresql://postgres:user@db:5432/smartpickup
    depends_on:
      - db

  admin-frontend:
    build: ./admin-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
